name: Bump Version and Publish to NPM

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 10

      - run: yarn
      - run: yarn run lint

  release:
    if: "!contains(github.event.head_commit.message, 'release') && !contains(github.event.head_commit.message, '[SKIP-CI]') && !contains(github.event.head_commit.message, '[SKIP CI]')"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: fregante/setup-git-user@v1

      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: yarn

      - name: Share PUSH_BRANCH between all steps in job
        run: echo "PUSH_BRANCH=`echo "$GITHUB_REF" | awk -F / '{ print $3 }'`" >> $GITHUB_ENV

      - name: Checkout to PUSH_BRANCH
        run: git checkout $PUSH_BRANCH

      - name: Bump version
        run: HUSKY_SKIP_HOOKS=1 npx standard-version

      - name: Build package
        run: yarn run build

      - name: Publish to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Push change log and version tag
        run: git push --follow-tags origin $PUSH_BRANCH
